# kind: KubeletConfiguration
# apiVersion: kubelet.config.k8s.io/v1beta1
# address: 127.0.0.1
# ---

apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
allowedUnsafeSysctls:
- "net.ipv4.tcp_congestion_control"

# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: kubelet-config-1.20
#   namespace: kube-system
# data:
#   kubelet: |
#     apiVersion: kubelet.config.k8s.io/v1beta1
#     kind: KubeletConfiguration
#     allowedUnsafeSysctls:
#       - "net.ipv4.tcp_congestion_control"
